# Generated by Django 5.2.4 on 2025-08-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Interview', 'Interview'), ('Offer', 'Offer'), ('Rejected', 'Rejected')], default='Applied', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('resume_score', models.IntegerField(default=0)),
                ('skills_matched', models.TextField(blank=True)),
            ],
        ),
    ]
