# Generated by Django 5.2.4 on 2025-08-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_jobapplication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='company_name',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='jobapplication',
            old_name='job_title',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='resume_score',
        ),
        migrations.RemoveField(
            model_name='jobapplication',
            name='skills_matched',
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(default='Applied', max_length=50),
        ),
    ]
